### PR TITLE
Renamed MySQL options

### PR DESCRIPTION
**Pull request by jruijgers**
On Ubuntu 16.04.1 mysql complains about the key_buffer and myisam-recover options.

A newer version of mysql (5.7) is installed here. According to the docs these are the correct names.

### CODE REVIEW

**Comment by Voronenko** [comment]
This ruins backward compability for existing deployments.
You hit this only on xenial, because it now has MySQL7 installed by default.

Even not all software is finally ported.

Thus better would be to have backward compability (i.e. detect version, and IF ...  THAN)

**Comment by jruijgers** [comment]
I added a new task with corresponding config file specific for MySQL 5.7

**Comment by Voronenko** [comment]
Yep, cool - but still duplication. - you have 85% common

Under version detection I meant smth like

tasks:
   - command: mysql --version
     name: ls
     register: mysql_version

and later use filter like  https://docs.ansible.com/ansible/playbooks_tests.html#version-comparison

   - template: ....
     when: {{ mysql_version | version_compare('5.7', '>=') }}

**Comment by jruijgers** [comment]
Updated with mysql version parsing and copying the correspoding file

**Pull request merged**
